### ISSUE TITLE
Mystery crash on exit when putting THaAnalyzer on the stack

### ISSUE THREAD

**Issue by hansenjo** [JeffersonLab/analyzer#63]
With more recent ROOT versions (tested 5.34/17 and 5.34/24), I get the following crash (with both analyzer 1.5 and 1.6). It seems to be CINT-related, but could be an awkward interaction. An old ROOT installation, 5.28, does not show this behavior, but unlike 5.34 does crash when doing the same with TBrowser.

21] fedora21:~ > analyzer

---
-                                              *
-            W E L C O M E  to  the            *
-       H A L L A   C++  A N A L Y Z E R       *
-                                              *
-        Release  1.6.0-devel      Jan 31 2015 *
-  Based on ROOT  5.34/24           Dec 2 2014 *
-                                              *
-            For information visit             *
-        http://hallaweb.jlab.org/root/        *
-                                              *
  ************************************************

CINT/ROOT C/C++ Interpreter version 5.18.00, July 2, 2010
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.
analyzer [0] THaAnalyzer a
analyzer [1] .q
analyzer [2] 

 **\* Break **\* segmentation violation

There was a crash.
This is the entire stack trace of all threads:
#0  0x00000039f96c451a in waitpid () from /lib64/libc.so.6
#1  0x00000039f9642a2b in do_system () from /lib64/libc.so.6
#2  0x00000039fcc7185f in TUnixSystem::StackTrace() () from /usr/lib64/root/libCore.so.5.34
#3  0x00000039fcc73b2c in TUnixSystem::DispatchSignals(ESignals) () from /usr/lib64/root/libCore.so.5.34
#4  <signal handler called>
#5  0x00000000014c6f90 in ?? ()
#6  0x00007f62271ecd64 in G__haDict_769_0_84 (result7=0x7fffb97c1b60, funcname=0x110bed0 "", libp=0x7fffb97c1ba0, hash=0) at haDict.C:25650
#7  0x00000039fbb2c5f3 in Cint::G__ExceptionWrapper(int (_)(G__value_, char const_, G__param_, int), G__value_, char_, G__param*, int) () from /usr/lib64/root/libCint.so.5.34
#8  0x00000039fba7cfe4 in G__execute_call () from /usr/lib64/root/libCint.so.5.34
#9  0x00000039fba7d3ec in G__call_cppfunc () from /usr/lib64/root/libCint.so.5.34
#10 0x00000039fbae628d in G__interpret_func () from /usr/lib64/root/libCint.so.5.34
#11 0x00000039fba5d513 in G__getfunction () from /usr/lib64/root/libCint.so.5.34
#12 0x00000039fbb59737 in G__destroy_upto () from /usr/lib64/root/libCint.so.5.34
#13 0x00000039fbb59dac in G__scratch_globals_upto () from /usr/lib64/root/libCint.so.5.34
#14 0x00000039fcc33050 in TCint::ResetGlobals() () from /usr/lib64/root/libCore.so.5.34
#15 0x00000039fcbc4eb1 in TROOT::EndOfProcessCleanups(bool) () from /usr/lib64/root/libCore.so.5.34
#16 0x00000039fcb93336 in TApplication::~TApplication() () from /usr/lib64/root/libCore.so.5.34
#17 0x00007f62270f4fcd in THaInterface::~THaInterface (this=0x112d900, __in_chrg=<optimized out>) at src/THaInterface.C:140
#18 0x00007f62270f5026 in THaInterface::~THaInterface (this=0x112d900, __in_chrg=<optimized out>) at src/THaInterface.C:159
#19 0x0000000000401601 in main (argc=1, argv=0x7fffb97cc968) at src/main.C:22

**Comment by hansenjo** [comment]
This no longer seems to happen with ROOT 5.34/36 (nor with ROOT 6.08/02). Closing this issue, assuming it was a ROOT bug.
